### ISSUE TITLE
OffscreenCanvas is landed on Firefox 47 Nightly

### ISSUE THREAD

**Issue by kyoshino** [mozilla/platatus#304] opened 2016-02-01 16:06 UTC
The 2D API is [now on Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=801176#c86).

**Comment by marco-c** [comment] 2016-02-08 10:43
It's still disabled by default: http://hg.mozilla.org/mozilla-central/file/4ca883690e2a/modules/libpref/init/all.js#l4295

**Comment by marco-c** [comment] 2016-02-08 10:44
Duplicate of #284.

**Closed by marco-c** 2016-02-08 10:44 UTC
Labels: duplicate
