### ISSUE TITLE
Add CSS status

### ISSUE THREAD

**Issue by yisibl** [mozilla/platatus#210] opened 2015-12-03 06:41 UTC
For example:

* CSS Grid Layout: https://bugzilla.mozilla.org/show_bug.cgi?id=616605

**Comment by digitarald** [comment] 2015-12-03 17:36
We also noticed a lack of CSS and design features. Duplicate of #168

**Closed by digitarald** 2015-12-03 17:36 UTC

**Comment by yisibl** [comment] 2015-12-04 01:37
Thanks!
